using System.Numerics;

namespace Prak03;

public class Program
{
    // Computes discrete log x for g^x ≡ h (mod p) using Baby-Step Giant-Step.
    // Assumes p is prime and g is a generator (or at least h is in ⟨g⟩).
    static BigInteger? BabyStepGiantStep(BigInteger g, BigInteger h, BigInteger p)
    {
        // Order of multiplicative group Z*_p is p-1
        var n = p - 1; // valid because p is prime

        // m = ceil(sqrt(n))
        var m = IntegerCeilingSqrt(n);

        // Precompute baby steps: g^j mod p for j in [0, m-1]
        var table = new Dictionary<BigInteger, BigInteger>(capacity: (int)BigInteger.Min(m, int.MaxValue));
        var gj = BigInteger.One;
        for (BigInteger j = 0; j < m; j++)
        {
            // Store smallest j for each value to be consistent
            if (!table.ContainsKey(gj)) table[gj] = j;
            gj = BigInteger.Remainder(gj * g, p);
        }

        // Compute factor = g^{-m} mod p using modular inverse via Fermat: g^{-1} = g^{p-2}
        // => g^{-m} = (g^{p-2})^m = g^{m(p-2)} mod p
        // More efficient: inv_g = g^{p-2}, then factor = inv_g^m
        
        var factor = BigInteger.ModPow(g, m * (p - 2), p);  // g^(m·(p-2)) = g^(-m)
        
        // var inv_g = BigInteger.ModPow(g, p - 2, p);
        // var factor = BigInteger.ModPow(inv_g, m, p);

        // Iterate giant steps: y_i = h * (g^{-m})^i mod p
        var gamma = h % p;
        for (BigInteger i = 0; i < m; i++)
        {
            if (table.TryGetValue(gamma, out var j))
            {
                var x = i * m + j;
                // Verify solution (defensive)
                if (BigInteger.ModPow(g, x, p) == h % p)
                    return x;
            }

            gamma = BigInteger.Remainder(gamma * factor, p);
        }

        return null; // no solution found (h not in subgroup generated by g)
    }
    
    public static BigInteger IntegerCeilingSqrt(BigInteger n)
    {
        if (n <= 0) return 0;
        var approx = (BigInteger)Math.Ceiling(Math.Sqrt((double)n));
    
        // Adjustiere nach unten bis approx² >= n und (approx-1)² < n
        while ((approx - 1) * (approx - 1) >= n)
            approx--;
    
        // Adjustiere nach oben bis approx² >= n
        while (approx * approx < n)
            approx++;
    
        return approx;
    }

    static void Main(string[] args)
    {
        Console.WriteLine("=".PadRight(70, '='));
        Console.WriteLine("Praktikum 3: Diskrete Logarithmen – Baby-Step Giant-Step");
        Console.WriteLine("=".PadRight(70, '='));
        Console.WriteLine();

        // Given parameters
        BigInteger p = BigInteger.Parse("6971096459");
        BigInteger g = new BigInteger(2);
        BigInteger h = BigInteger.Parse("4178319614");

        Console.WriteLine($"Given: p = {p}, g = {g}, h = {h}");
        Console.WriteLine("Goal: Find x such that g^x ≡ h (mod p)");
        Console.WriteLine();

        var start = DateTime.UtcNow;
        var x = BabyStepGiantStep(g, h, p);
        var elapsed = DateTime.UtcNow - start;

        if (x is null)
        {
            Console.WriteLine("No solution found (h is not in the subgroup generated by g).");
            return;
        }

        Console.WriteLine($"x = {x}");
        // Verify result
        var verify = BigInteger.ModPow(g, x.Value, p);
        Console.WriteLine($"Check: 2^{x} mod p = {verify}");
        Console.WriteLine($"Matches h? {(verify == h % p ? "YES" : "NO")}");
    }
}
